FROM golang:1.7.3
WORKDIR /go/src/github.com/camptocamp/terraboard
RUN go get github.com/aws/aws-sdk-go github.com/Sirupsen/logrus github.com/hashicorp/terraform github.com/mattn/go-sqlite3 github.com/jinzhu/gorm
COPY . .
RUN go install .
ENTRYPOINT ["terraboard"]
CMD [""]
