[[constraint]]
  branch = "master"
  name = "github.com/Sirupsen/logrus"

[[constraint]]
  branch = "master"
  name = "github.com/aws/aws-sdk-go"

[[constraint]]
  revision = "8b3b678c2fd9d76b194b2f4dc3eb0d1883c95863"
  name = "github.com/hashicorp/terraform"

[[constraint]]
  branch = "master"
  name = "github.com/jessevdk/go-flags"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/gorm"

[[constraint]]
  branch = "master"
  name = "github.com/pmezard/go-difflib"
