log:
  level: error
  format: json

database:
  host: postgres
  port: 15432
  user: terraboard-user
  password: terraboard-pass
  name: terraboard-db
  no-sync: true

aws:
  dynamodb-table: terraboard-dynamodb
  s3:
    bucket: terraboard-bucket
    key-prefix: test/
    file-extension: .tfstate

tfe:
  address: https://tfe.example.com
  token: foo
  organization: bar

gcp:
  gcs-bucket:
    - my-bucket-1
    - my-bucket-2
  gcp-sa-key-path: /path/to/key

gitlab:
  address: https://gitlab.example.com
  token: foo

web:
  port: 39090
  base-url: /test/
  logout-url: /test-logout
