name: Build-VueJS

on: [push, pull_request]

jobs:
  build-vue:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./static/terraboard-vuejs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup NodeJS
        uses: actions/setup-node@master

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build